pipeline {
    agent any

    environment {
        SCANNER_HOME = tool 'sonar-scanner'
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                url: 'https://github.com/zaid404x/CyberMinions.git'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('sonar-server') {
                    sh '''
                    $SCANNER_HOME/bin/sonar-scanner \
                    -Dsonar.projectName=CyberMinions \
                    -Dsonar.projectKey=CyberMinions \
                    -Dsonar.sources=. \
                    -Dsonar.host.url=http://localhost:9000
                    '''
                }
            }
        }

        stage('Trivy Filesystem Scan') {
            steps {
                sh 'trivy fs .'
            }
        }

        stage('Docker Build') {
            steps {
                sh 'docker build -t cyberminions:v1 .'
            }
        }

        stage('Trivy Image Scan') {
            steps {
                sh 'trivy image cyberminions:v1'
            }
        }

        stage('Docker Push') {
            steps {
                sh 'docker tag cyberminions:v1 zaidpathan31/cyberminions:v1'
                sh 'docker push zaidpathan31/cyberminions:v1'
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh '''
                kubectl apply -f k8s/deployment.yaml
                kubectl apply -f k8s/service.yaml
                kubectl rollout restart deployment/cyberminions-deployment
                '''
            }
        }

        stage('Verify Deployment') {
            steps {
                sh 'kubectl get pods'
                sh 'kubectl get svc'
            }
        }
    }

    post {
        success {
            echo '🚀 CyberMinions successfully deployed to Kubernetes!'
        }

        failure {
            echo '❌ Pipeline failed. Check console logs.'
        }
    }
}
